#-----------------------------------------------------------------------------+
# BMG - BudMan GUI
BMG_BASIC_FIXED_FONT = ("Consolas", 12)
BMG_BASIC_FIXED_FONT_BOLD = ("Consolas", 12, 'bold')
# Colors and Styles
BMG_BLACK = 'black'
BMG_TEXT_VALUE_COLOR = "blue"
BMG_FAINT_GRAY = '#ededed'
BMG_LIGHT_GRAY = '#D5D6D5'
BMG_DARK_TEXT = '#202020'
BMG_BUTTON_FOREGROUND_ACTIVE = '#FFFFFF'
BMG_BUTTON_FOREGROUND_ACTIVE = '#FFFFFF'
BMG_BUTTON_FOREGROUND_DISABLED = '#8EA6B4'
BMG_BUTTON_BACKGROUND_ACTIVE = '#007ACC'
BMG_BUTTON_BACKGROUND_DISABLED = BMG_LIGHT_GRAY
BMG_ENTRY_BACKGROUND_ACTIVE = '#E6DDC4'
# Geometry Constants
BMG_MIN_WINDOW_WIDTH = 1600
BMG_MIN_WINDOW_HEIGHT = 1200
BMG_MAX_WINDOW_WIDTH = 2000
BMG_MAX_WINDOW_HEIGHT = 2000
BMG_BUTTON_WIDTH = 20
BMG_STATUS_BAR_HEIGHT = 40
BMG_TFRAME_PADDING = 0
BMG_TNOTEBOOK_PADDING = 0
# BMG - UI Widget Tags
BMG_FTVOBJECT = "ftvobject"
BMG_WBTVOBJECT = "wbtvobject"
BMG_INFO = "INFO"
BMG_DEBUG = "DEBUG"
BMG_WARNING = "WARNING"
BMG_ERROR = "ERROR"
BMG_CRITICAL = "CRITICAL"
# BMG - String Constants
BMG_WINDOW_TITLE = "P3 Budget Manager"
BMG_APP_READY_STATUS = "Ready"
BMG_APP_STATUS_LABEL = "Status:"
BMG_APP_PROGRESS_LABEL = "Progress:"
BMG_APP_WINDOW_SIZE_LABEL = "Size:"
BMG_APP_USER_LABEL = "User:"
BMG_UNBOUND_WORKBOOK = "<unbound workbook>"
BMG_UNINITIALIZED = "<uninitialized>"
BMG_TREEVIEW_WORKBOOKS_TAB_LABEL = "Workbook View"
BMG_TREEVIEW_FILES_TAB_LABEL = "Files View"

