#-----------------------------------------------------------------------------+
# BMG - BudMan GUI
BMG_FAINT_GRAY = '#ededed'
BMG_LIGHT_GRAY = '#D5D6D5'
BMG_BUTTON_FOREGROUND_ACTIVE = '#FFFFFF'
BMG_BUTTON_FOREGROUND_ACTIVE = '#FFFFFF'
BMG_BUTTON_FOREGROUND_DISABLED = '#8EA6B4'
BMG_BUTTON_BACKGROUND_ACTIVE = '#007ACC'
BMG_BUTTON_BACKGROUND_DISABLED = BMG_LIGHT_GRAY
BMG_BUTTON_WIDTH = 20
BMG_ENTRY_BACKGROUND_ACTIVE = '#E6DDC4'
BMG_WINDOW_TITLE = "P3 Budget Manager"
BMG_MIN_WINDOW_WIDTH = 800
BMG_MIN_WINDOW_HEIGHT = 450
BMG_MAX_WINDOW_WIDTH = 1600
BMG_MAX_WINDOW_HEIGHT = 1000
BMG_STATUS_BAR_HEIGHT = 30
#-----------------------------------------------------------------------------+

